### ISSUE TITLE
 Preparing product data Lesson issue

### ISSUE THREAD

**Issue by briannabeauchamp** [briannabeauchamp/ecommerce-pattern-library#2]
I'm trying to go through the "Preparing product data" lesson and can't get my products to show up. I've created all of my product .md files. Don't really know what I'm doing wrong. @thomasjbradley

**Comment by thomasjbradley** [comment]
Everything looks set up properly except inside the `.md` files.

At the bottom of each file you need another set of `---`—the files start with three dashes and also end with three dashes.

**Comment by briannabeauchamp** [comment]
Am I meant to be able to see my products somewhere at this point?

**Comment by thomasjbradley** [comment]
Yep—you have to type their URLs into the browser. This one should work for you:

http://localhost:4000/products/cactus-blossom/

**Comment by briannabeauchamp** [comment]
Only the header and footer show up, I must be doing something else wrong...

**Comment by thomasjbradley** [comment]
There’s an error message in Terminal when I try to run it.

Right here is says get the `button/primary` pattern:
https://github.com/briannabeauchamp/ecommerce-pattern-library/blob/master/_patterns/cards/product-card.html#L7
But you don’t have a pattern named `primary`—you probably want `basic`

**Comment by briannabeauchamp** [comment]
Okay perfect, that worked but my button still isn't showing up.

**Comment by thomasjbradley** [comment]
In the card? Did you commit & push?

**Comment by briannabeauchamp** [comment]
Yes and yeah I have commit and pushed.

**Comment by thomasjbradley** [comment]
This button?

<img width="502" alt="Screen Shot 2020-03-23 at 7 19 17 PM" src="https://user-images.githubusercontent.com/105192/77372103-4a950680-6d3b-11ea-971e-a8fabe2b04f0.png">

**Comment by briannabeauchamp** [comment]
Yes but I mean when I click on the candle to go to the actual individual candle page, the buy now button disappears, is that normal?

**Comment by thomasjbradley** [comment]
Yeah, the button disappearing does make sense. There isn’t any button in this file:
https://github.com/briannabeauchamp/ecommerce-pattern-library/blob/master/_layouts/product.html

**Comment by briannabeauchamp** [comment]
Okay so I've now added a button, can you remind me how I add text to this button? Because at the moment it's a blank button. I want it to say "Add to Cart"

**Comment by briannabeauchamp** [comment]
Okay so I've fixed the button issue, but now I need to make a few changes because my products page looks nothing like it's supposed to. I don't want that paragraph of text to be there, I only want that text to be there when you click on the card to go to its individual page. Is there an easy way to change this? There's also supposed to be a title at the top. I've attached an image to show what I wanted it to look like.
<img width="382" alt="Screen Shot 2020-01-20 at 8 09 21 PM" src="https://user-images.githubusercontent.com/43150710/77467262-0f014780-6de2-11ea-8b68-3aee0fca2b16.png">

**Comment by thomasjbradley** [comment]
When you say ”products page” do you mean the ”list” or the page that shows only a single product?

**Comment by thomasjbradley** [comment]
Oh, nevermind—I figured it out.

**Comment by briannabeauchamp** [comment]
I don't want the paragraph to be there on the list page

**Comment by thomasjbradley** [comment]
*Heading—*

Put an `<h1>` into the `product.html` file:
https://github.com/briannabeauchamp/ecommerce-pattern-library/blob/master/products.html#L5

**Comment by thomasjbradley** [comment]
*Paragraph—*

Remove it from within the card pattern itself:
https://github.com/briannabeauchamp/ecommerce-pattern-library/blob/master/_patterns/cards/product-card.html#L5

**Comment by briannabeauchamp** [comment]
okay, done and done. Now how should I tackle the overall spacing?

**Comment by thomasjbradley** [comment]
`.gutter`?
`.wrapper`?
`.island`?

**Comment by briannabeauchamp** [comment]
Perfect, one last question regarding this lesson, my button is taking the whole width of my cards, why?

**Comment by thomasjbradley** [comment]
Did you commit & push that?

**Comment by briannabeauchamp** [comment]
yes

**Comment by thomasjbradley** [comment]
I’m not seeing the button problem. I still see this:

![Screen Shot 2020-03-24 at 3 49 52 PM](https://user-images.githubusercontent.com/105192/77470485-2131b480-6de7-11ea-97b7-4351577df494.png)

**Comment by briannabeauchamp** [comment]
This is what I'm seeing... have you refreshed it?
<img width="1183" alt="Screen Shot 2020-03-24 at 3 50 32 PM" src="https://user-images.githubusercontent.com/43150710/77470556-3d355600-6de7-11ea-8a70-5c7c0a027481.png">

**Comment by thomasjbradley** [comment]
I’m seeing that now. I must have been too impatient for Netlify.
Looking into the problem…

**Comment by thomasjbradley** [comment]
It’s because they have the `.block` class on them. They’re getting set to `display: block` which will then make the thing take up a whole line.

**Comment by briannabeauchamp** [comment]
Okay that fixed it, thanks.
