### ISSUE TITLE
Request for Grades

### ISSUE THREAD

**Issue by briannabeauchamp** [briannabeauchamp/ecommerce-pattern-library#3]
Requesting grades for the following lessons:
- Building pages with patterns
- The leftovers
- Preparing product data
- Jekyll generators

I believe I've done all I've had to do for these, but please feel free to let me know if I might have missed a step for any of these.
Thanks :)
@thomasjbradley

**Comment by thomasjbradley** [comment]
What did you do in your pattern library for “The leftovers”?
(The rest are good.)

**Comment by briannabeauchamp** [comment]
I didn't change anything for the leftovers lesson, I couldn't think of anything I would need. Can you suggest anything?

**Comment by briannabeauchamp** [comment]
Side note - I would also like to request grade for product list page template.

**Comment by thomasjbradley** [comment]
I see the product card pattern doesn’t have a description:
https://lucid-wilson-3d231b.netlify.com/pattern-library/#cards--product-card

Let’s fix that up and we’ll call “Leftovers” done.

**Comment by briannabeauchamp** [comment]
sounds good!

**Comment by briannabeauchamp** [comment]
Okay so I've added a description. I'll close this issue.
