### ISSUE TITLE
Homepage template - buttons issue

### ISSUE THREAD

**Issue by briannabeauchamp** [briannabeauchamp/ecommerce-pattern-library#4]
Hi again! Having a lot of trouble with my index.html buttons, can't quite figure out why... In my first banner there should be only one button that says view. 
In my candle cards, I can't get the text to show up on the button and also can't remember how to change the image so it's not the same in the three instances... 
Finally, can't get my text to show up in my bottom banner button either. 

SOS, I must have some wires crossed somewhere... @thomasjbradley

**Comment by briannabeauchamp** [comment]
On a side note, I would also like to specify a max-height on the second banner image, it is way too tall at the moment.

**Comment by thomasjbradley** [comment]
There are 2 buttons in the banner pattern:
https://github.com/briannabeauchamp/ecommerce-pattern-library/blob/master/_patterns/cards/spring-banner.html#L6
https://github.com/briannabeauchamp/ecommerce-pattern-library/blob/master/_patterns/cards/spring-banner.html#L8

---

This line of code needs another attribute, `text=include.button_text`:
https://github.com/briannabeauchamp/ecommerce-pattern-library/blob/master/_patterns/cards/candle.html#L4

**Comment by thomasjbradley** [comment]
Bottom banner is the same problem as above: `text=include.button_text`

**Comment by briannabeauchamp** [comment]
That fixed it, thanks.

**Comment by briannabeauchamp** [comment]
Can you remind me how to change the image so it's not the same in the three instances of my homepage candle cards?

**Comment by thomasjbradley** [comment]
Add an placeholder variable here:
https://github.com/briannabeauchamp/ecommerce-pattern-library/blob/master/_patterns/cards/candle.html#L3
Something like `{{include.title}}`

Then on the homepage you need to add a new attribute to the cards, `title=""`:
https://github.com/briannabeauchamp/ecommerce-pattern-library/blob/master/index.html#L11

```html
{% pattern cards/candle button_text="View" button_url="/products/" title="" %}
```

**Comment by briannabeauchamp** [comment]
It changed the title on every card, but the image hasn't changed?

**Comment by briannabeauchamp** [comment]
So I have the title working, but how do I link up the images?

**Comment by thomasjbradley** [comment]
Same way, except putting another include placeholder in the images’s `src` attribute.

**Comment by briannabeauchamp** [comment]
I've tried to do that and all it did was remove the image completely. In the candle.html file I put {{include.image}} and then in my index.html did image="candle.jpg". Am I putting the wrong info into the index file?

**Comment by thomasjbradley** [comment]
Don’t forget `/images/`

**Comment by briannabeauchamp** [comment]
thank you!

**Comment by briannabeauchamp** [comment]
Why is it that when I click on the view button on my candle cards it won't go to my products page?

**Comment by thomasjbradley** [comment]
We need to add a `url` attribute to these lines:
https://github.com/briannabeauchamp/ecommerce-pattern-library/blob/master/index.html#L11-L13

```
url="/products/cactus-blossom/"
```

**Comment by briannabeauchamp** [comment]
I've added that to the first one and it's still not working

**Comment by thomasjbradley** [comment]
Oh, I see. Try changing `include.data.url` to just `include.url`:
https://github.com/briannabeauchamp/ecommerce-pattern-library/blob/master/_patterns/cards/candle.html#L4

**Comment by briannabeauchamp** [comment]
perfect thanks

**Comment by briannabeauchamp** [comment]
Okay so I'd like to request a grade for Homepage Template then please.

**Comment by thomasjbradley** [comment]
👍
